const express = require("express")
const cors = require("cors")
const authRoutes = require("./routes/authRoutes")
const customerRoutes = require("./routes/customerRoutes")
const productRoutes = require("./routes/productRoutes")
const invoiceRoutes = require("./routes/invoiceRoutes")
const app = express()
app.use(cors())
app.use(express.json())
app.use("/api/auth",authRoutes)
app.use("/api/customers",customerRoutes)
app.use("/api/products",productRoutes)
app.use("/api/invoices",invoiceRoutes)
app.listen(5000,()=>{console.log("API running on 5000")})
