CREATE DATABASE invoice_saas;
USE invoice_saas;
CREATE TABLE users(id INT AUTO_INCREMENT PRIMARY KEY,email VARCHAR(255),password VARCHAR(255));
CREATE TABLE customers(id INT AUTO_INCREMENT PRIMARY KEY,company VARCHAR(255),ico VARCHAR(20),dic VARCHAR(20),address TEXT);
CREATE TABLE products(id INT AUTO_INCREMENT PRIMARY KEY,name VARCHAR(255),price DECIMAL(10,2),vat INT);
CREATE TABLE invoices(id INT AUTO_INCREMENT PRIMARY KEY,invoice_number VARCHAR(50),customer_id INT,total DECIMAL(10,2));
CREATE TABLE invoice_items(id INT AUTO_INCREMENT PRIMARY KEY,invoice_id INT,product_id INT,quantity INT);
